spring:
  application.name: T1AcademyLimits
  mvc:
    resources:
      add-mappings: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "admin"
    password: "admin"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:/changelog/db/changelog-master.yaml
server:
  port: 8083